name: SST CI

on:
  push:
    branches:
      - dev
      - main

env:
  CI: true
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.8.0]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Extract branch name
      id: branch
      run: echo "RAW_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.8.0
        cache: 'npm'

    - name: Install Dependencies
      run: npm install --frozen-lockfile

    - name: Deploy to Prod
      if: env.RAW_BRANCH == 'main'
      run: npm run deploy:prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Deploy to Dev
      if: env.RAW_BRANCH == 'dev'
      run: npm run deploy:dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
