name: SST CI

on:
  push:
    branches:
      - dev
      - main

env:
  CI: true
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.2]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Extract branch name
      id: branch
      run: echo "RAW_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
        cache: 'npm'

    - name: Install SST ION cli
      run: curl -fsSL https://ion.sst.dev/install | bash

    - name: Install Dependencies
      run: npm install --frozen-lockfile

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_PROFILE: personal
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile personal
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile personal
        aws configure set default.region $AWS_DEFAULT_REGION --profile personal   
    
    - name: List Profiles
      run: aws configure list-profiles

    - name: Deploy to Prod
      if: env.RAW_BRANCH == 'main'
      run: AWS_PROFILE=personal npm run deploy:prod
    
    - name: Deploy to Dev
      if: env.RAW_BRANCH == 'dev'
      run: AWS_PROFILE=personal npm run deploy:dev
