name: SST CI

on:
  push:
    branches:
      - dev
      - main

env:
  CI: true
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.2]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Extract branch name
      id: branch
      run: echo "RAW_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
        cache: 'npm'

    - name: Install SST ION cli
      run: curl -fsSL https://ion.sst.dev/install | bash

    - name: Install Dependencies
      run: npm install --frozen-lockfile

    - name: Add profile credentials to ~/.aws/credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile personal
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile personal

    - name: Deploy to Prod
      if: env.RAW_BRANCH == 'main'
      run: npm run deploy:prod
    
    - name: Deploy to Dev
      if: env.RAW_BRANCH == 'dev'
      run: npm run deploy:dev
